### ISSUE TITLE
Сделать переносы для длинных названий событий при hover

### ISSUE THREAD

**Issue by ademaro** [makehtml/calendar-issues#1]
Может можно мини-скролинг сделать в блоке даты
То есть, навели курсор на пункт, строка переносится ниже, и все пункты ниже уходят будто в "скрытый список" вниз, но если поскролить ниже внутри блока, все пункты на месте

**Comment by Tom826** [comment]
Да, тоже отображается :)

**Comment by ademaro** [comment]
Поправлено

**Comment by Tom826** [comment]
Выглядит супер, спасибо! :)
